INFO:werkzeug:127.0.0.1 - - [27/May/2020 21:32:42] "[37mGET /session HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [27/May/2020 21:32:56] "[37mGET /session HTTP/1.1[0m" 200 -
DEBUG:root:Received POST request to session view
DEBUG:root:creating new session workspace for session Unnamed Session (08617d3c-0af0-4ebe-8820-c008399ebc16)
DEBUG:root:workspace created! (./data\08617d3c-0af0-4ebe-8820-c008399ebc16)
INFO:werkzeug:127.0.0.1 - - [27/May/2020 21:33:58] "[37mPOST /session HTTP/1.1[0m" 201 -
ERROR:root:Unable to read metadata for session 08617d3c-0af0-4ebe-8820-c008399ebc16
Traceback (most recent call last):
  File "C:\Users\brads\projects\tsdlv\server\src\tsdlv\session\session_view.py", line 55, in get
    with open(metadata_path, 'r') as metadata_file:
FileNotFoundError: [Errno 2] No such file or directory: './data\\08617d3c-0af0-4ebe-8820-c008399ebc16\\.metadata'
INFO:werkzeug:127.0.0.1 - - [27/May/2020 21:34:01] "[37mGET /session HTTP/1.1[0m" 200 -
DEBUG:root:configuration: {'session_data_loc': './data'}
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
DEBUG:root:Received POST request to session view
DEBUG:root:creating new session workspace for session Unnamed Session (b23a6c15-976b-4493-afce-a1ad247768d2)
DEBUG:root:workspace created! (./data\b23a6c15-976b-4493-afce-a1ad247768d2)
INFO:werkzeug:127.0.0.1 - - [27/May/2020 21:35:33] "[37mPOST /session HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [27/May/2020 21:35:36] "[37mGET /session HTTP/1.1[0m" 200 -
DEBUG:root:configuration: {'session_data_loc': './data'}
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [27/May/2020 22:12:38] "[33mGET /session/b23a6c15-976b-4493-afce-a1ad247768d2/files HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [27/May/2020 22:12:47] "[32mGET /session/b23a6c15-976b-4493-afce-a1ad247768d2/file HTTP/1.1[0m" 308 -
DEBUG:root:Received GET request to session file view
INFO:werkzeug:127.0.0.1 - - [27/May/2020 22:12:47] "[37mGET /session/b23a6c15-976b-4493-afce-a1ad247768d2/file/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [27/May/2020 22:14:30] "[32mPOST /session/b23a6c15-976b-4493-afce-a1ad247768d2/file HTTP/1.1[0m" 308 -
DEBUG:root:Received POST request to session file view
ERROR:root:Unable to update metadata file at ./data\b23a6c15-976b-4493-afce-a1ad247768d2\.metadata
Traceback (most recent call last):
  File "C:\Users\brads\projects\tsdlv\server\src\tsdlv\session\session_file_view.py", line 40, in post
    metadata = json.loads(metadata_file.read())
io.UnsupportedOperation: not readable
INFO:werkzeug:127.0.0.1 - - [27/May/2020 22:14:30] "[35m[1mPOST /session/b23a6c15-976b-4493-afce-a1ad247768d2/file/ HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [27/May/2020 22:16:06] "[32mPOST /session HTTP/1.1[0m" 308 -
DEBUG:root:Received POST request to session view
DEBUG:root:creating new session workspace for session Unnamed Session (63b3d17a-d73d-4744-9313-356b38bd949a)
DEBUG:root:workspace created! (./data\63b3d17a-d73d-4744-9313-356b38bd949a)
INFO:werkzeug:127.0.0.1 - - [27/May/2020 22:16:06] "[37mPOST /session/ HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [27/May/2020 22:16:15] "[32mGET /session HTTP/1.1[0m" 308 -
INFO:werkzeug:127.0.0.1 - - [27/May/2020 22:16:16] "[37mGET /session/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [27/May/2020 22:17:24] "[32mGET /session/63b3d17a-d73d-4744-9313-356b38bd949a/file HTTP/1.1[0m" 308 -
DEBUG:root:Received GET request to session file view
INFO:werkzeug:127.0.0.1 - - [27/May/2020 22:17:25] "[37mGET /session/63b3d17a-d73d-4744-9313-356b38bd949a/file/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [27/May/2020 22:18:19] "[32mPOST /session/63b3d17a-d73d-4744-9313-356b38bd949a/file HTTP/1.1[0m" 308 -
DEBUG:root:Received POST request to session file view
ERROR:root:Unable to update metadata file at ./data\63b3d17a-d73d-4744-9313-356b38bd949a\.metadata
Traceback (most recent call last):
  File "C:\Users\brads\projects\tsdlv\server\src\tsdlv\session\session_file_view.py", line 40, in post
    metadata = json.loads(metadata_file.read())
io.UnsupportedOperation: not readable
INFO:werkzeug:127.0.0.1 - - [27/May/2020 22:18:19] "[35m[1mPOST /session/63b3d17a-d73d-4744-9313-356b38bd949a/file/ HTTP/1.1[0m" 500 -
DEBUG:root:configuration: {'session_data_loc': './data'}
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [27/May/2020 22:20:01] "[32mPOST /session HTTP/1.1[0m" 308 -
DEBUG:root:Received POST request to session view
DEBUG:root:creating new session workspace for session Unnamed Session (011a5af8-dd4d-47db-b272-e56f58e21b21)
DEBUG:root:workspace created! (./data\011a5af8-dd4d-47db-b272-e56f58e21b21)
INFO:werkzeug:127.0.0.1 - - [27/May/2020 22:20:02] "[37mPOST /session/ HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [27/May/2020 22:20:19] "[32mPOST /session/011a5af8-dd4d-47db-b272-e56f58e21b21/file HTTP/1.1[0m" 308 -
DEBUG:root:Received POST request to session file view
ERROR:tsdlv:Exception on /session/011a5af8-dd4d-47db-b272-e56f58e21b21/file/ [POST]
Traceback (most recent call last):
  File "C:\Users\brads\projects\tsdlv\server\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\brads\projects\tsdlv\server\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\brads\projects\tsdlv\server\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\brads\projects\tsdlv\server\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\brads\projects\tsdlv\server\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\brads\projects\tsdlv\server\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\brads\projects\tsdlv\server\venv\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\brads\projects\tsdlv\server\venv\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "C:\Users\brads\projects\tsdlv\server\src\tsdlv\session\session_file_view.py", line 39, in post
    with open(metadata_path, mode="rw") as metadata_file:
ValueError: must have exactly one of create/read/write/append mode
INFO:werkzeug:127.0.0.1 - - [27/May/2020 22:20:20] "[35m[1mPOST /session/011a5af8-dd4d-47db-b272-e56f58e21b21/file/ HTTP/1.1[0m" 500 -
DEBUG:root:configuration: {'session_data_loc': './data'}
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [27/May/2020 22:21:28] "[32mPOST /session/011a5af8-dd4d-47db-b272-e56f58e21b21/file HTTP/1.1[0m" 308 -
DEBUG:root:Received POST request to session file view
ERROR:root:Unable to update metadata file at ./data\011a5af8-dd4d-47db-b272-e56f58e21b21\.metadata
Traceback (most recent call last):
  File "C:\Users\brads\projects\tsdlv\server\src\tsdlv\session\session_file_view.py", line 40, in post
    metadata = json.loads(metadata_file.read())
io.UnsupportedOperation: not readable
INFO:werkzeug:127.0.0.1 - - [27/May/2020 22:21:29] "[35m[1mPOST /session/011a5af8-dd4d-47db-b272-e56f58e21b21/file/ HTTP/1.1[0m" 500 -
